version: "3.0"

services:
    database:
        image: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: db
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
        ports: 
            - "5432:5432"
